### ISSUE TITLE
No home folder except library.

### ISSUE THREAD

**Issue by YehudaBialik** [gregneagle/pycreateuserpkg#21]
I created the package using pycreateuserpkg, 

`python createuserpkg --name=nimda --uid=505 --password=xxxx --admin --version=1.0 --identifier=lan.bialik.create_nimda.pkg /Users/xadmin/Desktop/create_nimda.pkg`

then I added it to a manifest in munki server, which installed it on the client. The resulting account has a Library folder in the home folder, but nothing else, plus when I log in I get an error message (not surprising) "A keychain cannot be found to store localdevice..."

I have a feeling that I'm not using this script correctly.

**Comment by gregneagle** [comment]
You are probably using the script correctly.

It creates a pkg which, when installed, creates a user account in the local Directory Services store.

User accounts and user home folder are not the same thing.

The package does _not_ create a home folder for the user. Typically, macOS will create that home folder in /Users on the first login for that account.

In your case, something else is creating the folder with partial contents before the user has a chance to login. Taking a look at the contents of that Library folder you are seeing might give you some clues as to what is creating it.

We saw something similar a while back and it was CrashPlan creating files before the user had logged in. We changed our CrashPlan deployment to not install CrashPlan until after there was an active user and the problem was addressed for us.

I'm going to close this issue as your problem is not really an issue with the createuserpkg tool.
